import type { PcbBoard } from "./types";

export const PRESET_ESP32_IOT_GATEWAY: PcbBoard = {
  id: "board-esp32-s3-gateway",
  title: "ESP32-S3 IoT Edge Gateway & Sensor Node",
  version: "1.2.0",
  author: "NO Hardware AI Team",
  description:
    "High-speed 2.4GHz Wi-Fi/BLE edge node with USB-C PD power, LiPo charger (TP4056), I2C BME280 barometric sensor, WS2812B status RGB, and 3.3V LDO regulator.",
  dimensions: {
    widthMm: 60,
    heightMm: 40,
    cornerRadiusMm: 3,
  },
  layersCount: 2,
  copperThicknessOz: 1,
  substrate: "FR4 (Er = 4.4, tanδ = 0.02)",
  components: [
    {
      id: "u1",
      ref: "U1",
      name: "ESP32-S3-WROOM-1-N16R8",
      category: "mcu",
      package: "Module-40P",
      x: 34,
      y: 20,
      rotation: 0,
      layer: "top",
      widthMm: 18,
      heightMm: 25.5,
      value: "Dual-core Xtensa 240MHz",
      description: "Primary wireless microcontroller with PCB trace antenna",
      lcscPartNumber: "C2913200",
      unitCostUsd: 3.2,
      pins: [
        { number: "1", name: "GND", net: "GND", relX: -9, relY: -10 },
        { number: "2", name: "3V3", net: "+3V3", relX: -9, relY: -8 },
        { number: "3", name: "EN", net: "ESP_EN", relX: -9, relY: -6 },
        { number: "4", name: "IO4", net: "I2C_SDA", relX: -9, relY: -4 },
        { number: "5", name: "IO5", net: "I2C_SCL", relX: -9, relY: -2 },
        { number: "14", name: "IO14", net: "WS2812_DIN", relX: -9, relY: 4 },
        { number: "19", name: "USB_D-", net: "USB_DN", relX: -9, relY: 8 },
        { number: "20", name: "USB_D+", net: "USB_DP", relX: -9, relY: 10 },
        { number: "40", name: "GND", net: "GND", relX: 9, relY: -10 },
      ],
    },
    {
      id: "j1",
      ref: "J1",
      name: "TYPE-C-31-M-12",
      category: "connector",
      package: "USB-C-16P",
      x: 6,
      y: 20,
      rotation: 90,
      layer: "top",
      widthMm: 9,
      heightMm: 7.5,
      value: "16-pin Reversible",
      description: "USB 2.0 Full Speed & 5V 3A Power Input",
      lcscPartNumber: "C165948",
      unitCostUsd: 0.35,
      pins: [
        { number: "A1", name: "GND", net: "GND", relX: -3.5, relY: -2 },
        { number: "A4", name: "VBUS", net: "+5V_USB", relX: -1.5, relY: -2 },
        { number: "A5", name: "CC1", net: "USB_CC1", relX: -0.5, relY: -2 },
        { number: "A6", name: "DP1", net: "USB_DP", relX: 0.5, relY: -2 },
        { number: "A7", name: "DN1", net: "USB_DN", relX: 1.5, relY: -2 },
        { number: "B1", name: "GND", net: "GND", relX: -3.5, relY: 2 },
        { number: "B4", name: "VBUS", net: "+5V_USB", relX: -1.5, relY: 2 },
        { number: "B5", name: "CC2", net: "USB_CC2", relX: -0.5, relY: 2 },
      ],
    },
    {
      id: "u2",
      ref: "U2",
      name: "AMS1117-3.3",
      category: "power",
      package: "SOT-223",
      x: 16,
      y: 10,
      rotation: 0,
      layer: "top",
      widthMm: 6.5,
      heightMm: 3.5,
      value: "3.3V 1A LDO",
      description: "Low-dropout voltage regulator from 5V to 3.3V rail",
      lcscPartNumber: "C6186",
      unitCostUsd: 0.12,
      pins: [
        { number: "1", name: "ADJ/GND", net: "GND", relX: -2.3, relY: 2 },
        { number: "2", name: "VOUT", net: "+3V3", relX: 0, relY: 2 },
        { number: "3", name: "VIN", net: "+5V_USB", relX: 2.3, relY: 2 },
        { number: "4", name: "TAB", net: "+3V3", relX: 0, relY: -2 },
      ],
    },
    {
      id: "u3",
      ref: "U3",
      name: "TP4056-42-ESOP8",
      category: "power",
      package: "ESOP-8",
      x: 16,
      y: 30,
      rotation: 0,
      layer: "top",
      widthMm: 5,
      heightMm: 4,
      value: "1A LiPo Charger",
      description: "Linear 1-cell Li-ion battery charger with thermal regulation",
      lcscPartNumber: "C16581",
      unitCostUsd: 0.18,
      pins: [
        { number: "1", name: "TEMP", net: "GND", relX: -2, relY: -1.5 },
        { number: "2", name: "PROG", net: "CHG_PROG", relX: -2, relY: -0.5 },
        { number: "3", name: "GND", net: "GND", relX: -2, relY: 0.5 },
        { number: "4", name: "VCC", net: "+5V_USB", relX: -2, relY: 1.5 },
        { number: "5", name: "BAT", net: "+VBAT", relX: 2, relY: 1.5 },
        { number: "6", name: "STDBY", net: "CHG_STDBY", relX: 2, relY: 0.5 },
        { number: "7", name: "CHRG", net: "CHG_STAT", relX: 2, relY: -0.5 },
        { number: "8", name: "CE", net: "+5V_USB", relX: 2, relY: -1.5 },
      ],
    },
    {
      id: "u4",
      ref: "U4",
      name: "BME280",
      category: "sensor",
      package: "LGA-8",
      x: 52,
      y: 10,
      rotation: 0,
      layer: "top",
      widthMm: 2.5,
      heightMm: 2.5,
      value: "Pressure / Temp / Humidity",
      description: "Digital environmental sensor via I2C",
      lcscPartNumber: "C92489",
      unitCostUsd: 1.85,
      pins: [
        { number: "1", name: "GND", net: "GND", relX: -1, relY: -1 },
        { number: "2", name: "CSB", net: "+3V3", relX: -1, relY: 0 },
        { number: "3", name: "SDI", net: "I2C_SDA", relX: -1, relY: 1 },
        { number: "4", name: "SCK", net: "I2C_SCL", relX: 1, relY: 1 },
        { number: "5", name: "SDO", net: "GND", relX: 1, relY: 0 },
        { number: "6", name: "VDDIO", net: "+3V3", relX: 1, relY: -0.5 },
        { number: "8", name: "VDD", net: "+3V3", relX: 1, relY: -1 },
      ],
    },
    {
      id: "d1",
      ref: "D1",
      name: "WS2812B-B",
      category: "led",
      package: "LED-5050",
      x: 52,
      y: 30,
      rotation: 0,
      layer: "top",
      widthMm: 5,
      heightMm: 5,
      value: "RGB Addressable LED",
      description: "Single-wire digital RGB status indicator",
      lcscPartNumber: "C114586",
      unitCostUsd: 0.08,
      pins: [
        { number: "1", name: "VDD", net: "+5V_USB", relX: -2, relY: -2 },
        { number: "2", name: "DOUT", net: "NC", relX: -2, relY: 2 },
        { number: "3", name: "VSS", net: "GND", relX: 2, relY: 2 },
        { number: "4", name: "DIN", net: "WS2812_DIN", relX: 2, relY: -2 },
      ],
    },
    {
      id: "c1",
      ref: "C1",
      name: "10µF 16V X5R",
      category: "passive",
      package: "0805",
      x: 12,
      y: 7,
      rotation: 90,
      layer: "top",
      widthMm: 2,
      heightMm: 1.25,
      value: "10µF",
      description: "LDO Input Filter Capacitor",
      lcscPartNumber: "C15850",
      unitCostUsd: 0.02,
      pins: [
        { number: "1", name: "1", net: "+5V_USB", relX: 0, relY: -0.8 },
        { number: "2", name: "2", net: "GND", relX: 0, relY: 0.8 },
      ],
    },
    {
      id: "c2",
      ref: "C2",
      name: "22µF 10V X5R",
      category: "passive",
      package: "0805",
      x: 20,
      y: 7,
      rotation: 90,
      layer: "top",
      widthMm: 2,
      heightMm: 1.25,
      value: "22µF",
      description: "LDO Output Bulk Capacitor",
      lcscPartNumber: "C45783",
      unitCostUsd: 0.03,
      pins: [
        { number: "1", name: "1", net: "+3V3", relX: 0, relY: -0.8 },
        { number: "2", name: "2", net: "GND", relX: 0, relY: 0.8 },
      ],
    },
    {
      id: "c3",
      ref: "C3",
      name: "100nF 50V X7R",
      category: "passive",
      package: "0603",
      x: 24,
      y: 13,
      rotation: 0,
      layer: "top",
      widthMm: 1.6,
      heightMm: 0.8,
      value: "100nF",
      description: "ESP32 VDD High-Frequency Decoupling Cap",
      lcscPartNumber: "C14663",
      unitCostUsd: 0.01,
      pins: [
        { number: "1", name: "1", net: "+3V3", relX: -0.7, relY: 0 },
        { number: "2", name: "2", net: "GND", relX: 0.7, relY: 0 },
      ],
    },
    {
      id: "r1",
      ref: "R1",
      name: "5.1k 1% 0603",
      category: "passive",
      package: "0603",
      x: 4,
      y: 12,
      rotation: 90,
      layer: "top",
      widthMm: 1.6,
      heightMm: 0.8,
      value: "5.1kΩ",
      description: "USB-C CC1 Pull-Down",
      lcscPartNumber: "C23186",
      unitCostUsd: 0.005,
      pins: [
        { number: "1", name: "1", net: "USB_CC1", relX: 0, relY: -0.7 },
        { number: "2", name: "2", net: "GND", relX: 0, relY: 0.7 },
      ],
    },
    {
      id: "r2",
      ref: "R2",
      name: "5.1k 1% 0603",
      category: "passive",
      package: "0603",
      x: 4,
      y: 28,
      rotation: 90,
      layer: "top",
      widthMm: 1.6,
      heightMm: 0.8,
      value: "5.1kΩ",
      description: "USB-C CC2 Pull-Down",
      lcscPartNumber: "C23186",
      unitCostUsd: 0.005,
      pins: [
        { number: "1", name: "1", net: "USB_CC2", relX: 0, relY: -0.7 },
        { number: "2", name: "2", net: "GND", relX: 0, relY: 0.7 },
      ],
    },
    {
      id: "r3",
      ref: "R3",
      name: "4.7k 1% 0603",
      category: "passive",
      package: "0603",
      x: 48,
      y: 6,
      rotation: 0,
      layer: "top",
      widthMm: 1.6,
      heightMm: 0.8,
      value: "4.7kΩ",
      description: "I2C SDA Pull-Up Resistor",
      lcscPartNumber: "C23164",
      unitCostUsd: 0.005,
      pins: [
        { number: "1", name: "1", net: "I2C_SDA", relX: -0.7, relY: 0 },
        { number: "2", name: "2", net: "+3V3", relX: 0.7, relY: 0 },
      ],
    },
    {
      id: "r4",
      ref: "R4",
      name: "4.7k 1% 0603",
      category: "passive",
      package: "0603",
      x: 48,
      y: 9,
      rotation: 0,
      layer: "top",
      widthMm: 1.6,
      heightMm: 0.8,
      value: "4.7kΩ",
      description: "I2C SCL Pull-Up Resistor",
      lcscPartNumber: "C23164",
      unitCostUsd: 0.005,
      pins: [
        { number: "1", name: "1", net: "I2C_SCL", relX: -0.7, relY: 0 },
        { number: "2", name: "2", net: "+3V3", relX: 0.7, relY: 0 },
      ],
    },
  ],
  nets: [
    {
      id: "net-gnd",
      name: "GND",
      type: "ground",
      voltage: 0,
      currentEstA: 2.0,
      color: "#38bdf8",
      pins: ["U1.1", "U1.40", "J1.A1", "J1.B1", "U2.1", "U3.1", "U3.3", "U4.1", "U4.5", "D1.3", "C1.2", "C2.2", "C3.2", "R1.2", "R2.2"],
    },
    {
      id: "net-5v",
      name: "+5V_USB",
      type: "power",
      voltage: 5.0,
      currentEstA: 1.5,
      color: "#ef4444",
      pins: ["J1.A4", "J1.B4", "U2.3", "U3.4", "U3.8", "D1.1", "C1.1"],
    },
    {
      id: "net-3v3",
      name: "+3V3",
      type: "power",
      voltage: 3.3,
      currentEstA: 0.8,
      color: "#f59e0b",
      pins: ["U2.2", "U2.4", "U1.2", "C2.1", "C3.1", "U4.2", "U4.6", "U4.8", "R3.2", "R4.2"],
    },
    {
      id: "net-usb-dp",
      name: "USB_DP",
      type: "differential",
      voltage: 3.3,
      currentEstA: 0.05,
      targetImpedance: 90,
      color: "#10b981",
      pins: ["J1.A6", "U1.20"],
    },
    {
      id: "net-usb-dn",
      name: "USB_DN",
      type: "differential",
      voltage: 3.3,
      currentEstA: 0.05,
      targetImpedance: 90,
      color: "#06b6d4",
      pins: ["J1.A7", "U1.19"],
    },
    {
      id: "net-sda",
      name: "I2C_SDA",
      type: "signal",
      voltage: 3.3,
      currentEstA: 0.01,
      color: "#8b5cf6",
      pins: ["U1.4", "U4.3", "R3.1"],
    },
    {
      id: "net-scl",
      name: "I2C_SCL",
      type: "signal",
      voltage: 3.3,
      currentEstA: 0.01,
      color: "#ec4899",
      pins: ["U1.5", "U4.4", "R4.1"],
    },
    {
      id: "net-ws2812",
      name: "WS2812_DIN",
      type: "signal",
      voltage: 3.3,
      currentEstA: 0.02,
      color: "#eab308",
      pins: ["U1.14", "D1.4"],
    },
  ],
  traces: [
    // Power traces
    {
      id: "tr-5v-1",
      net: "+5V_USB",
      layer: "F.Cu",
      widthMm: 0.8,
      clearanceMm: 0.25,
      points: [
        [6, 18],
        [10, 18],
        [12, 10],
        [18.3, 10],
      ],
    },
    {
      id: "tr-3v3-1",
      net: "+3V3",
      layer: "F.Cu",
      widthMm: 0.6,
      clearanceMm: 0.25,
      points: [
        [16, 12],
        [20, 12],
        [24, 12],
        [25, 12],
      ],
    },
    {
      id: "tr-3v3-2",
      net: "+3V3",
      layer: "F.Cu",
      widthMm: 0.5,
      clearanceMm: 0.2,
      points: [
        [25, 12],
        [40, 12],
        [48, 8],
        [51, 9],
      ],
    },
    // USB Differential pair
    {
      id: "tr-usb-dp",
      net: "USB_DP",
      layer: "F.Cu",
      widthMm: 0.25,
      clearanceMm: 0.2,
      points: [
        [6.5, 20.5],
        [12, 23],
        [20, 27],
        [25, 30],
      ],
    },
    {
      id: "tr-usb-dn",
      net: "USB_DN",
      layer: "F.Cu",
      widthMm: 0.25,
      clearanceMm: 0.2,
      points: [
        [7.5, 21.5],
        [13, 24],
        [21, 28],
        [25, 28],
      ],
    },
    // I2C Signal traces
    {
      id: "tr-sda",
      net: "I2C_SDA",
      layer: "B.Cu",
      widthMm: 0.2,
      clearanceMm: 0.2,
      points: [
        [25, 16],
        [32, 8],
        [44, 6],
        [51, 9],
      ],
    },
    {
      id: "tr-scl",
      net: "I2C_SCL",
      layer: "B.Cu",
      widthMm: 0.2,
      clearanceMm: 0.2,
      points: [
        [25, 18],
        [34, 10],
        [46, 7],
        [53, 9],
      ],
    },
    // WS2812 DIN
    {
      id: "tr-din",
      net: "WS2812_DIN",
      layer: "F.Cu",
      widthMm: 0.25,
      clearanceMm: 0.2,
      points: [
        [25, 24],
        [35, 26],
        [45, 28],
        [50, 28],
      ],
    },
  ],
  vias: [
    { id: "via-1", net: "I2C_SDA", x: 25, y: 16, drillMm: 0.3, padMm: 0.6 },
    { id: "via-2", net: "I2C_SDA", x: 51, y: 9, drillMm: 0.3, padMm: 0.6 },
    { id: "via-3", net: "I2C_SCL", x: 25, y: 18, drillMm: 0.3, padMm: 0.6 },
    { id: "via-4", net: "I2C_SCL", x: 53, y: 9, drillMm: 0.3, padMm: 0.6 },
    { id: "via-gnd-1", net: "GND", x: 12, y: 8, drillMm: 0.3, padMm: 0.6 },
    { id: "via-gnd-2", net: "GND", x: 20, y: 8, drillMm: 0.3, padMm: 0.6 },
    { id: "via-gnd-3", net: "GND", x: 24.7, y: 13, drillMm: 0.3, padMm: 0.6 },
    { id: "via-gnd-4", net: "GND", x: 34, y: 32, drillMm: 0.3, padMm: 0.6 },
    { id: "via-gnd-5", net: "GND", x: 45, y: 35, drillMm: 0.3, padMm: 0.6 },
    { id: "via-gnd-6", net: "GND", x: 54, y: 32, drillMm: 0.3, padMm: 0.6 },
  ],
  copperPours: [
    { net: "GND", layer: "B.Cu", thermalRelief: true },
    { net: "GND", layer: "F.Cu", thermalRelief: true },
  ],
};

export const PRESET_BUCK_CONVERTER: PcbBoard = {
  id: "board-buck-converter-3a",
  title: "12V/24V to 5V 3A Synchronous Buck Regulator",
  version: "2.0.0",
  author: "NO Hardware AI Team",
  description:
    "High-efficiency (>94%) 500kHz step-down DC-DC switching regulator with low thermal loop area, shielded SMD power inductor, and ceramic output ripple filters.",
  dimensions: {
    widthMm: 45,
    heightMm: 35,
    cornerRadiusMm: 2.5,
  },
  layersCount: 2,
  copperThicknessOz: 2, // Heavy 2oz copper for 3A continuous
  substrate: "FR4 High-Tg (Tg > 170°C)",
  components: [
    {
      id: "u1",
      ref: "U1",
      name: "MP2307DN",
      category: "ic",
      package: "SOIC-8-EP",
      x: 22,
      y: 18,
      rotation: 0,
      layer: "top",
      widthMm: 5,
      heightMm: 4,
      value: "3A 340kHz Sync Buck",
      description: "Synchronous step-down converter with exposed thermal pad",
      lcscPartNumber: "C14258",
      unitCostUsd: 0.65,
      pins: [
        { number: "1", name: "BS", net: "BOOT", relX: -2, relY: -1.5 },
        { number: "2", name: "IN", net: "+VIN_12V", relX: -2, relY: -0.5 },
        { number: "3", name: "SW", net: "SW_NODE", relX: -2, relY: 0.5 },
        { number: "4", name: "GND", net: "GND", relX: -2, relY: 1.5 },
        { number: "5", name: "FB", net: "VFB", relX: 2, relY: 1.5 },
        { number: "6", name: "COMP", net: "COMP_NET", relX: 2, relY: 0.5 },
        { number: "7", name: "EN", net: "+VIN_12V", relX: 2, relY: -0.5 },
        { number: "8", name: "SS", net: "SS_NET", relX: 2, relY: -1.5 },
      ],
    },
    {
      id: "l1",
      ref: "L1",
      name: "10µH 4.5A Shielded Inductor",
      category: "passive",
      package: "SMD-7070",
      x: 31,
      y: 18,
      rotation: 0,
      layer: "top",
      widthMm: 7,
      heightMm: 7,
      value: "10µH",
      description: "Power inductor with saturation current > 4.5A",
      lcscPartNumber: "C497812",
      unitCostUsd: 0.42,
      pins: [
        { number: "1", name: "1", net: "SW_NODE", relX: -3.2, relY: 0 },
        { number: "2", name: "2", net: "+5V_OUT", relX: 3.2, relY: 0 },
      ],
    },
    {
      id: "cin1",
      ref: "C_IN1",
      name: "10µF 50V X7R 1210",
      category: "passive",
      package: "1210",
      x: 14,
      y: 16,
      rotation: 90,
      layer: "top",
      widthMm: 3.2,
      heightMm: 2.5,
      value: "10µF 50V",
      description: "Input Decoupling High-Voltage Ceramic",
      lcscPartNumber: "C96411",
      unitCostUsd: 0.15,
      pins: [
        { number: "1", name: "1", net: "+VIN_12V", relX: 0, relY: -1.2 },
        { number: "2", name: "2", net: "GND", relX: 0, relY: 1.2 },
      ],
    },
    {
      id: "cout1",
      ref: "C_OUT1",
      name: "22µF 16V X7R 1206",
      category: "passive",
      package: "1206",
      x: 39,
      y: 18,
      rotation: 90,
      layer: "top",
      widthMm: 3.2,
      heightMm: 1.6,
      value: "22µF 16V",
      description: "Output Low-ESR Filter",
      lcscPartNumber: "C14253",
      unitCostUsd: 0.08,
      pins: [
        { number: "1", name: "1", net: "+5V_OUT", relX: 0, relY: -1.0 },
        { number: "2", name: "2", net: "GND", relX: 0, relY: 1.0 },
      ],
    },
    {
      id: "j_in",
      ref: "J_IN",
      name: "Terminal Block 5.08mm 2P",
      category: "connector",
      package: "TB-5.08-2P",
      x: 6,
      y: 18,
      rotation: 0,
      layer: "top",
      widthMm: 10,
      heightMm: 8,
      value: "12V-24V Input",
      description: "Heavy DC input screw terminal",
      lcscPartNumber: "C8395",
      unitCostUsd: 0.25,
      pins: [
        { number: "1", name: "VIN+", net: "+VIN_12V", relX: 0, relY: -2.54 },
        { number: "2", name: "GND", net: "GND", relX: 0, relY: 2.54 },
      ],
    },
    {
      id: "j_out",
      ref: "J_OUT",
      name: "Terminal Block 5.08mm 2P",
      category: "connector",
      package: "TB-5.08-2P",
      x: 41,
      y: 18,
      rotation: 0,
      layer: "top",
      widthMm: 10,
      heightMm: 8,
      value: "5V 3A Output",
      description: "Regulated 5V output connector",
      lcscPartNumber: "C8395",
      unitCostUsd: 0.25,
      pins: [
        { number: "1", name: "VOUT+", net: "+5V_OUT", relX: 0, relY: -2.54 },
        { number: "2", name: "GND", net: "GND", relX: 0, relY: 2.54 },
      ],
    },
  ],
  nets: [
    {
      id: "net-gnd",
      name: "GND",
      type: "ground",
      voltage: 0,
      currentEstA: 3.5,
      pins: ["U1.4", "C_IN1.2", "C_OUT1.2", "J_IN.2", "J_OUT.2"],
    },
    {
      id: "net-vin",
      name: "+VIN_12V",
      type: "power",
      voltage: 12.0,
      currentEstA: 1.6,
      pins: ["J_IN.1", "C_IN1.1", "U1.2", "U1.7"],
    },
    {
      id: "net-sw",
      name: "SW_NODE",
      type: "power",
      voltage: 12.0,
      currentEstA: 3.5,
      pins: ["U1.3", "L1.1"],
    },
    {
      id: "net-vout",
      name: "+5V_OUT",
      type: "power",
      voltage: 5.0,
      currentEstA: 3.0,
      pins: ["L1.2", "C_OUT1.1", "J_OUT.1"],
    },
  ],
  traces: [
    {
      id: "tr-vin-power",
      net: "+VIN_12V",
      layer: "F.Cu",
      widthMm: 1.5,
      clearanceMm: 0.3,
      points: [
        [6, 15.5],
        [14, 14.8],
        [20, 17.5],
      ],
    },
    {
      id: "tr-sw-power",
      net: "SW_NODE",
      layer: "F.Cu",
      widthMm: 1.8,
      clearanceMm: 0.35,
      points: [
        [20, 18.5],
        [27.8, 18],
      ],
    },
    {
      id: "tr-vout-power",
      net: "+5V_OUT",
      layer: "F.Cu",
      widthMm: 1.6,
      clearanceMm: 0.3,
      points: [
        [34.2, 18],
        [39, 17],
        [41, 15.5],
      ],
    },
  ],
  vias: [
    { id: "via-gnd-ep1", net: "GND", x: 22, y: 18, drillMm: 0.3, padMm: 0.6 },
    { id: "via-gnd-ep2", net: "GND", x: 21, y: 17, drillMm: 0.3, padMm: 0.6 },
    { id: "via-gnd-ep3", net: "GND", x: 23, y: 17, drillMm: 0.3, padMm: 0.6 },
    { id: "via-gnd-ep4", net: "GND", x: 21, y: 19, drillMm: 0.3, padMm: 0.6 },
    { id: "via-gnd-ep5", net: "GND", x: 23, y: 19, drillMm: 0.3, padMm: 0.6 },
  ],
  copperPours: [
    { net: "GND", layer: "F.Cu", thermalRelief: true },
    { net: "GND", layer: "B.Cu", thermalRelief: true },
  ],
};

export const PRESET_ROBOTICS_MOTOR_CONTROLLER: PcbBoard = {
  id: "board-robotics-bldc-driver",
  title: "40A High-Power BLDC Robotics Inverter & Field Oriented Control",
  version: "2.1.0",
  author: "NO Hardware AI Team",
  description:
    "Triple half-bridge inverter with DRV8302 gate driver, 60V 120A MOSFETs, 3-phase current shunt amplifiers, and Aluminum IMS thermal substrate for robotic actuators.",
  dimensions: {
    widthMm: 75,
    heightMm: 50,
    cornerRadiusMm: 4,
  },
  layersCount: 4,
  copperThicknessOz: 3, // 3oz heavy copper
  substrate: "Aluminum Insulated Metal Substrate (IMS, 2.5 W/m-K)",
  boardType: "ims-aluminum",
  solderMaskColor: "matte-grey",
  surfaceFinish: "ENIG",
  enclosureMaterial: "aluminum-6061",
  components: [
    {
      id: "u1-drv",
      ref: "U1",
      name: "DRV8302-3Phase-Gate-Driver",
      category: "ic",
      package: "HTSSOP-56",
      x: 28,
      y: 25,
      rotation: 0,
      layer: "top",
      widthMm: 14,
      heightMm: 8,
      value: "60V Gate Driver with Buck",
      description: "Integrated dual current shunt amplifiers and buck regulator",
      lcscPartNumber: "C78531",
      unitCostUsd: 5.4,
      pins: [
        { number: "1", name: "GND", net: "GND", relX: -7, relY: -3 },
        { number: "10", name: "PVDD", net: "+24V_BAT", relX: -7, relY: -1 },
        { number: "25", name: "GH_A", net: "GATE_HA", relX: 7, relY: -3 },
        { number: "26", name: "SH_A", net: "PHASE_A", relX: 7, relY: -2 },
        { number: "35", name: "GH_B", net: "GATE_HB", relX: 7, relY: 1 },
        { number: "45", name: "GH_C", net: "GATE_HC", relX: 7, relY: 3 },
      ],
    },
    {
      id: "q1-ha",
      ref: "Q1",
      name: "CSD19532Q5B-60V-100A",
      category: "power",
      package: "SON-8-5x6",
      x: 48,
      y: 15,
      rotation: 90,
      layer: "top",
      widthMm: 5,
      heightMm: 6,
      value: "60V 2.5mΩ N-Ch",
      description: "High-side Phase A Power MOSFET",
      lcscPartNumber: "C148281",
      unitCostUsd: 1.8,
      pins: [
        { number: "1", name: "S", net: "PHASE_A", relX: -2, relY: -2 },
        { number: "4", name: "G", net: "GATE_HA", relX: -2, relY: 2 },
        { number: "5", name: "D", net: "+24V_BAT", relX: 2, relY: 0 },
      ],
    },
    {
      id: "q2-la",
      ref: "Q2",
      name: "CSD19532Q5B-60V-100A",
      category: "power",
      package: "SON-8-5x6",
      x: 48,
      y: 28,
      rotation: 90,
      layer: "top",
      widthMm: 5,
      heightMm: 6,
      value: "60V 2.5mΩ N-Ch",
      description: "Low-side Phase A Power MOSFET",
      lcscPartNumber: "C148281",
      unitCostUsd: 1.8,
      pins: [
        { number: "1", name: "S", net: "SHUNT_A", relX: -2, relY: -2 },
        { number: "4", name: "G", net: "GATE_LA", relX: -2, relY: 2 },
        { number: "5", name: "D", net: "PHASE_A", relX: 2, relY: 0 },
      ],
    },
    {
      id: "r-shunt",
      ref: "R_SH1",
      name: "WSL2512-1mR-1%",
      category: "passive",
      package: "2512-SMD",
      x: 48,
      y: 40,
      rotation: 0,
      layer: "top",
      widthMm: 6.4,
      heightMm: 3.2,
      value: "0.001Ω 3W",
      description: "Kelvin-sense low-inductance phase current shunt",
      lcscPartNumber: "C154210",
      unitCostUsd: 0.95,
      pins: [
        { number: "1", name: "1", net: "SHUNT_A", relX: -2.8, relY: 0 },
        { number: "2", name: "2", net: "GND", relX: 2.8, relY: 0 },
      ],
    },
    {
      id: "j-motor",
      ref: "J_MOT",
      name: "XT60PB-Angle-Connector",
      category: "connector",
      package: "XT60-HighCurrent",
      x: 66,
      y: 25,
      rotation: 0,
      layer: "top",
      widthMm: 12,
      heightMm: 16,
      value: "60A Continuous Gold",
      description: "Motor Phase U/V/W and Battery DC Input",
      lcscPartNumber: "C2938102",
      unitCostUsd: 1.4,
      pins: [
        { number: "1", name: "PH_A", net: "PHASE_A", relX: 0, relY: -6 },
        { number: "2", name: "PH_B", net: "PHASE_B", relX: 0, relY: 0 },
        { number: "3", name: "PH_C", net: "PHASE_C", relX: 0, relY: 6 },
      ],
    },
  ],
  nets: [
    { id: "net-gnd", name: "GND", type: "ground", currentEstA: 35.0, pins: ["U1.1", "R_SH1.2"] },
    { id: "net-vbat", name: "+24V_BAT", type: "power", voltage: 24, currentEstA: 30.0, pins: ["U1.10", "Q1.5"] },
    { id: "net-pha", name: "PHASE_A", type: "power", voltage: 24, currentEstA: 40.0, pins: ["Q1.1", "Q2.5", "J_MOT.1"] },
  ],
  traces: [
    {
      id: "tr-phase-a",
      net: "PHASE_A",
      layer: "F.Cu",
      widthMm: 3.2, // Heavy copper polygon
      clearanceMm: 0.5,
      points: [
        [48, 15],
        [48, 25],
        [66, 19],
      ],
    },
    {
      id: "tr-vbat-heavy",
      net: "+24V_BAT",
      layer: "F.Cu",
      widthMm: 3.0,
      clearanceMm: 0.5,
      points: [
        [50, 15],
        [58, 15],
      ],
    },
  ],
  vias: [
    { id: "v-mot-gnd1", net: "GND", x: 48, y: 44, drillMm: 0.4, padMm: 0.8 },
    { id: "v-mot-gnd2", net: "GND", x: 50, y: 44, drillMm: 0.4, padMm: 0.8 },
    { id: "v-mot-gnd3", net: "GND", x: 52, y: 44, drillMm: 0.4, padMm: 0.8 },
  ],
  copperPours: [
    { net: "GND", layer: "F.Cu", thermalRelief: true },
    { net: "GND", layer: "B.Cu", thermalRelief: true },
  ],
};

export const PRESET_FLIGHT_CONTROLLER_AVIONICS: PcbBoard = {
  id: "board-drone-autopilot-h7",
  title: "Aerospace High-Speed Autopilot Flight Controller",
  version: "3.0.0",
  author: "NO Hardware AI Team",
  description:
    "6-layer controlled impedance avionics board with 480MHz STM32H743, vibration-isolated dual IMUs (BMI270 + ICM42688), BMP388 barometer, CAN-FD bus, and 8x DShot ESC outputs.",
  dimensions: {
    widthMm: 36,
    heightMm: 36,
    cornerRadiusMm: 4,
  },
  layersCount: 6,
  copperThicknessOz: 1,
  substrate: "High-Tg Isola 370HR (Tg 180°C, Dk 4.04)",
  boardType: "rigid",
  solderMaskColor: "stealth-black",
  surfaceFinish: "ENIG",
  enclosureMaterial: "aluminum-6061",
  components: [
    {
      id: "u-mcu-h7",
      ref: "U1",
      name: "STM32H743VIT6-480MHz",
      category: "mcu",
      package: "LQFP-100",
      x: 18,
      y: 18,
      rotation: 0,
      layer: "top",
      widthMm: 16,
      heightMm: 16,
      value: "ARM Cortex-M7 480MHz 2MB Flash",
      description: "Main Flight Management Unit with Hardware FPU & DSP",
      lcscPartNumber: "C190282",
      unitCostUsd: 11.5,
      pins: [
        { number: "1", name: "VDD", net: "+3V3_MCU", relX: -7, relY: -7 },
        { number: "25", name: "SPI1_SCK", net: "IMU1_SCK", relX: -7, relY: 7 },
        { number: "50", name: "CAN_TX", net: "CAN_TX", relX: 7, relY: 7 },
        { number: "75", name: "GND", net: "GND", relX: 7, relY: -7 },
      ],
    },
    {
      id: "u-imu-1",
      ref: "U2",
      name: "BMI270-6Axis-IMU",
      category: "sensor",
      package: "LGA-14",
      x: 7,
      y: 7,
      rotation: 0,
      layer: "top",
      widthMm: 3,
      heightMm: 2.5,
      value: "Ultra-low noise Gyro/Accel",
      description: "Primary Gyroscope with internal anti-aliasing filter",
      lcscPartNumber: "C284910",
      unitCostUsd: 3.8,
      pins: [
        { number: "1", name: "VDD", net: "+3V3_SENS", relX: -1, relY: -1 },
        { number: "2", name: "GND", net: "GND", relX: -1, relY: 1 },
      ],
    },
    {
      id: "u-can",
      ref: "U3",
      name: "TCAN334GD-CANFD",
      category: "ic",
      package: "SOIC-8",
      x: 29,
      y: 7,
      rotation: 0,
      layer: "top",
      widthMm: 5,
      heightMm: 4,
      value: "5Mbps CAN-FD Transceiver",
      description: "DroneCAN avionics bus transceiver with ±30V bus fault protection",
      lcscPartNumber: "C115829",
      unitCostUsd: 1.25,
      pins: [
        { number: "1", name: "TXD", net: "CAN_TX", relX: -2, relY: -1 },
        { number: "6", name: "CANH", net: "CAN_H", relX: 2, relY: 1 },
      ],
    },
  ],
  nets: [
    { id: "net-gnd-flight", name: "GND", type: "ground", currentEstA: 2.5, pins: ["U1.75", "U2.2"] },
    { id: "net-3v3-flight", name: "+3V3_MCU", type: "power", voltage: 3.3, currentEstA: 0.6, pins: ["U1.1"] },
  ],
  traces: [
    {
      id: "tr-imu-clock",
      net: "IMU1_SCK",
      layer: "F.Cu",
      widthMm: 0.2,
      clearanceMm: 0.25,
      points: [
        [11, 11],
        [7, 7],
      ],
    },
  ],
  vias: [
    { id: "vf-gnd1", net: "GND", x: 4, y: 4, drillMm: 0.3, padMm: 0.6 },
    { id: "vf-gnd2", net: "GND", x: 32, y: 4, drillMm: 0.3, padMm: 0.6 },
    { id: "vf-gnd3", net: "GND", x: 4, y: 32, drillMm: 0.3, padMm: 0.6 },
    { id: "vf-gnd4", net: "GND", x: 32, y: 32, drillMm: 0.3, padMm: 0.6 },
  ],
  copperPours: [
    { net: "GND", layer: "F.Cu", thermalRelief: true },
    { net: "GND", layer: "B.Cu", thermalRelief: true },
  ],
};

export const PRESET_SEWER_INSPECTION_ROBOT: PcbBoard = {
  id: "board-sewer-crawler-v1",
  title: "Astra-Pipe: Autonomous Pipeline Crawler & NDT Inspection Core",
  version: "2.4.0",
  author: "NO Hardware Architecture Core",
  description:
    "Industrial IP68 in-pipe crawler electronics: Dual BLDC motor drivers (DRV8353RS), 1.0MHz ultrasonic wall-thickness NDT transceiver, Alphasense H2S + NDIR CH4 hazardous gas sensing, 48V-to-5V step-down umbilical power, and 480MHz STM32H7 primary controller.",
  dimensions: {
    widthMm: 110,
    heightMm: 52,
    cornerRadiusMm: 4,
  },
  layersCount: 6,
  copperThicknessOz: 2,
  substrate: "Polyimide / High-Tg FR4 (TG170, CTI 600)",
  components: [
    {
      id: "u1-mcu",
      ref: "U1",
      name: "STM32H743VIT6",
      category: "mcu",
      package: "LQFP-100",
      x: 35,
      y: 26,
      rotation: 0,
      layer: "top",
      widthMm: 16,
      heightMm: 16,
      value: "480MHz ARM Cortex-M7",
      description: "Primary Real-Time Core: dual CAN-FD, 16-bit ADCs for ultrasonic NDT, FOC motor timing",
      lcscPartNumber: "C407338",
      unitCostUsd: 14.8,
      pins: [
        { number: "1", name: "VDD", net: "+3V3_CORE", relX: -7, relY: -6 },
        { number: "2", name: "GND", net: "GND", relX: -7, relY: -4 },
        { number: "14", name: "CAN1_RX", net: "CAN_RX", relX: -7, relY: 2 },
        { number: "15", name: "CAN1_TX", net: "CAN_TX", relX: -7, relY: 4 },
        { number: "50", name: "US_TRIG", net: "US_PULSE_TRIG", relX: 7, relY: -6 },
        { number: "51", name: "US_ADC_IN", net: "US_ECHO_AMP", relX: 7, relY: -4 },
        { number: "80", name: "PWM_A", net: "MOTOR_PWM_A", relX: 0, relY: 7 },
        { number: "81", name: "PWM_B", net: "MOTOR_PWM_B", relX: 2, relY: 7 },
        { number: "82", name: "PWM_C", net: "MOTOR_PWM_C", relX: 4, relY: 7 },
      ],
    },
    {
      id: "u2-drv",
      ref: "U2",
      name: "DRV8353RS-Q1",
      category: "ic",
      package: "VQFN-48",
      x: 75,
      y: 26,
      rotation: 0,
      layer: "top",
      widthMm: 7,
      heightMm: 7,
      value: "100V 3-Phase Gate Driver",
      description: "Automotive high-voltage crawler motor driver with three integrated current shunt amplifiers",
      lcscPartNumber: "C193582",
      unitCostUsd: 6.5,
      pins: [
        { number: "1", name: "VM", net: "+48V_BUS", relX: -3, relY: -3 },
        { number: "10", name: "GHA", net: "GATE_HA", relX: 3, relY: -3 },
        { number: "11", name: "GLA", net: "GATE_LA", relX: 3, relY: -1 },
        { number: "12", name: "GHB", net: "GATE_HB", relX: 3, relY: 1 },
        { number: "13", name: "GLB", net: "GATE_LB", relX: 3, relY: 3 },
      ],
    },
    {
      id: "u3-ultrasound",
      ref: "U3",
      name: "TX7316-US-PULSER",
      category: "ic",
      package: "BGA-64",
      x: 18,
      y: 15,
      rotation: 0,
      layer: "top",
      widthMm: 8,
      heightMm: 8,
      value: "16-Channel High-Voltage Pulser",
      description: "Non-Destructive Ultrasonic pulse transmitter (1-5MHz) for pipe wall thickness & crack depth",
      lcscPartNumber: "C882109",
      unitCostUsd: 19.4,
      pins: [
        { number: "A1", name: "HV_POS", net: "+70V_US_HV", relX: -3, relY: -3 },
        { number: "B1", name: "OUT1", net: "US_TRANSDUCER_1", relX: 3, relY: -3 },
      ],
    },
    {
      id: "u4-gas-afe",
      ref: "U4",
      name: "LMP91000-AFE",
      category: "ic",
      package: "WSON-14",
      x: 18,
      y: 38,
      rotation: 0,
      layer: "top",
      widthMm: 4,
      heightMm: 4,
      value: "Potentiostat Gas AFE",
      description: "Electrochemical sensor front-end for Alphasense H2S (Hydrogen Sulfide) toxic sewer gas detection",
      lcscPartNumber: "C138841",
      unitCostUsd: 3.8,
      pins: [
        { number: "1", name: "WE", net: "H2S_WORK_ELECTRODE", relX: -1.5, relY: -1 },
        { number: "2", name: "RE", net: "H2S_REF_ELECTRODE", relX: -1.5, relY: 1 },
        { number: "7", name: "VOUT", net: "H2S_ANALOG_OUT", relX: 1.5, relY: 0 },
      ],
    },
    {
      id: "u5-power-buck",
      ref: "U5",
      name: "LM5164-Q1",
      category: "power",
      package: "SOIC-8-EP",
      x: 95,
      y: 15,
      rotation: 0,
      layer: "top",
      widthMm: 5,
      heightMm: 4,
      value: "100V 1A Synchronous Buck",
      description: "Umbilical power step-down: 48V-100V DC transmission line down to 5.0V system bus",
      lcscPartNumber: "C392019",
      unitCostUsd: 2.15,
      pins: [
        { number: "1", name: "VIN", net: "+48V_BUS", relX: -2, relY: -1 },
        { number: "2", name: "SW", net: "SW_NODE_5V", relX: 2, relY: -1 },
        { number: "3", name: "FB", net: "FB_5V", relX: 2, relY: 1 },
        { number: "4", name: "GND", net: "GND", relX: -2, relY: 1 },
      ],
    },
    {
      id: "j1-umbilical",
      ref: "J1",
      name: "M12-8P-IP68-WATERPROOF",
      category: "connector",
      package: "M12-Panel-Mount",
      x: 8,
      y: 26,
      rotation: 90,
      layer: "top",
      widthMm: 12,
      heightMm: 12,
      value: "M12 8-Pin IP68 Submersible",
      description: "Hermetic tether connection: 48V DC power, CAN-FD differential bus, and high-speed coax video",
      lcscPartNumber: "C902410",
      unitCostUsd: 11.2,
      pins: [
        { number: "1", name: "DC_48V+", net: "+48V_BUS", relX: -3, relY: -3 },
        { number: "2", name: "DC_48V-", net: "GND", relX: -3, relY: 3 },
        { number: "3", name: "CAN_H", net: "CAN_H", relX: 3, relY: -2 },
        { number: "4", name: "CAN_L", net: "CAN_L", relX: 3, relY: 2 },
      ],
    },
    {
      id: "l1-power",
      ref: "L1",
      name: "Bourns SRP1265A",
      category: "passive",
      package: "SMD-1265",
      x: 95,
      y: 35,
      rotation: 0,
      layer: "top",
      widthMm: 13,
      heightMm: 13,
      value: "10µH / 9.5A Shielded",
      description: "Low-DCR high-temperature inductor for high-efficiency umbilical power step-down",
      lcscPartNumber: "C420119",
      unitCostUsd: 1.85,
      pins: [
        { number: "1", name: "1", net: "SW_NODE_5V", relX: -5, relY: 0 },
        { number: "2", name: "2", net: "+5V0_SYS", relX: 5, relY: 0 },
      ],
    },
  ],
  nets: [
    { id: "net-48v", name: "+48V_BUS", type: "power", voltage: 48, currentEstA: 6.0, pins: ["J1.1", "U5.1", "U2.1"] },
    { id: "net-gnd-sewer", name: "GND", type: "ground", currentEstA: 8.0, pins: ["J1.2", "U1.2", "U5.4"] },
    { id: "net-5v-sys", name: "+5V0_SYS", type: "power", voltage: 5.0, currentEstA: 3.5, pins: ["L1.2"] },
    { id: "net-3v3-core", name: "+3V3_CORE", type: "power", voltage: 3.3, currentEstA: 1.2, pins: ["U1.1"] },
    { id: "net-can-h", name: "CAN_H", type: "differential", voltage: 3.3, currentEstA: 0.1, pins: ["J1.3"] },
    { id: "net-can-l", name: "CAN_L", type: "differential", voltage: 3.3, currentEstA: 0.1, pins: ["J1.4"] },
    { id: "net-us-trans", name: "US_TRANSDUCER_1", type: "signal", voltage: 70, currentEstA: 0.8, pins: ["U3.OUT1"] },
  ],
  traces: [
    {
      id: "tr-48v-bus",
      net: "+48V_BUS",
      layer: "F.Cu",
      widthMm: 1.8,
      clearanceMm: 0.8,
      points: [
        [8, 26],
        [75, 26],
        [95, 15],
      ],
    },
    {
      id: "tr-sw-power",
      net: "SW_NODE_5V",
      layer: "F.Cu",
      widthMm: 1.4,
      clearanceMm: 0.6,
      points: [
        [95, 15],
        [95, 35],
      ],
    },
  ],
  vias: [
    { id: "vs-gnd1", net: "GND", x: 12, y: 12, drillMm: 0.4, padMm: 0.8 },
    { id: "vs-gnd2", net: "GND", x: 98, y: 12, drillMm: 0.4, padMm: 0.8 },
    { id: "vs-gnd3", net: "GND", x: 12, y: 44, drillMm: 0.4, padMm: 0.8 },
    { id: "vs-gnd4", net: "GND", x: 98, y: 44, drillMm: 0.4, padMm: 0.8 },
  ],
  copperPours: [
    { net: "GND", layer: "F.Cu", thermalRelief: true },
    { net: "GND", layer: "B.Cu", thermalRelief: true },
  ],
};
